### ISSUE TITLE
nuumber of multi-edge node pair

### ISSUE THREAD

**Issue by mjafarpour87** [EhsanBitaraf/triple-a#14]
this is an interesting metric that is available in Cytoscape. It indicates how often neighboring nodes are linked by more than one edge. it is computed for multi-graphs and basically counts the number of edges between pairs of neighbor nodes.
https://med.bioinf.mpi-inf.mpg.de/netanalyzer/help/2.6.1/#neighbor

**Comment by EhsanBitaraf** [comment]
`num_components = nx.number_connected_components(G)`
