### ISSUE TITLE
average shortest path length (per node)

### ISSUE THREAD

**Issue by mjafarpour87** [EhsanBitaraf/triple-a#17]
It is necessary to calculate the average shortest path length for each node.

**Comment by EhsanBitaraf** [comment]
The average shortest-path length is typically calculated per graph. This metric provides a measure of the overall efficiency of the network in terms of how well connected its nodes are to each other. To calculate the average shortest-path length for a graph, you would first find the shortest path between every pair of nodes in the graph, and then take the average of these shortest paths. This metric can be useful in a variety of fields, such as transportation planning, social network analysis, and communication networks, among others.

It is possible to calculate the average shortest-path length for each node in a graph using some specialized measures, such as the "closeness centrality" or the "harmonic centrality". 

Closeness centrality is a measure that reflects how close a node is to all other nodes in the network. The closeness centrality of a node is calculated as the reciprocal of the sum of its distances to all other nodes in the graph.

Harmonic centrality is another measure that takes into account the harmonic mean distance from a node to every other node in the network. It is calculated by taking the reciprocal of the sum of the distances between a node and every other node in the graph.

Both of these measures can be used to calculate the average shortest-path length for each node in a graph, providing a measure of how central each node is to the overall connectivity of the network.

Here's an example of how to calculate the average shortest-path length for each node in a graph using NetworkX in Python:

```python
import networkx as nx

# Define your graph, for example:
G = nx.Graph()
G.add_edge(1, 2)
G.add_edge(1, 3)
G.add_edge(2, 4)

# Calculate the average shortest-path length for each node
avg_shortest_path_lengths = nx.shortest_path_length(G)

# Print the results
for node in avg_shortest_path_lengths:
    avg_shortest_path_length = sum(avg_shortest_path_lengths[node].values()) / (len(G) - 1)
    print(f"The average shortest-path length for node {node} is {avg_shortest_path_length:.2f}")
```

This will output the following:
```
The average shortest-path length for node 1 is 1.33
The average shortest-path length for node 2 is 1.67
The average shortest-path length for node 3 is 2.00
The average shortest-path length for node 4 is 2.00
```

**Comment by EhsanBitaraf** [comment]
It was done, but its unit test should be finalized.
