### ISSUE TITLE
clustering coefficient (per node)

### ISSUE THREAD

**Issue by mjafarpour87** [EhsanBitaraf/triple-a#18]
we need to have an estimation of clustering coefficient on directed networks. This metric should be calculated per node.

**Comment by EhsanBitaraf** [comment]
To calculate the clustering coefficient for a directed network, we need to first define what we mean by "clustering coefficient" in this context. 

In an undirected graph, the clustering coefficient of a node measures the degree to which its neighbors are also connected to each other. However, in a directed graph, we have two types of neighbors: incoming (i.e., nodes that have edges pointing towards the node) and outgoing (i.e., nodes that have edges pointing away from the node). 

One way to define clustering coefficient in a directed graph is to consider only the connections between a node's incoming and outgoing neighbors. Specifically, we can define the clustering coefficient of a node as the fraction of possible connections between its incoming and outgoing neighbors that actually exist. This is sometimes called the "directed clustering coefficient". 

To calculate the directed clustering coefficient for a given node, we can follow these steps:

1. Identify all incoming and outgoing neighbors of the node.
2. Count the number of connections that exist between the incoming and outgoing neighbors.
3. Calculate the total number of possible connections between the incoming and outgoing neighbors (which is the product of the number of incoming neighbors and the number of outgoing neighbors).
4. Divide the number of existing connections by the total number of possible connections.

This gives us the directed clustering coefficient for the node, which will be a value between 0 and 1.

Note that there are other ways to define clustering coefficient in directed graphs, such as considering cycles of length 2 or 3 that involve the node. The approach I described above is one possible definition, but depending on your specific use case you may want to consider alternative definitions.

**Comment by EhsanBitaraf** [comment]
added `get_clustering_coefficient_per_node()`
